/**
 * P15-P4b — Google Discover image-eligibility audit (NON-BLOCKING: always
 * exits 0 unless DISCOVER_AUDIT_STRICT=true; Discover readiness is a warning
 * budget, not a build gate).
 *
 * For every built article page (JSON-LD @type Article):
 *   - extracts og:image and the Article schema image
 *   - verifies the large variant: OG endpoints (/og/...) are 1200×630 by
 *     construction; local files are measured with sharp (already a dep);
 *     remote CMS media can't be measured offline → reported UNVERIFIED.
 *   - flags anything provably < 1200px wide (DISCOVER_IMG_MIN).
 *
 * Report: docs/seo/discover-audit.md (committed — the P4 gate artifact).
 *
 * Usage (after npm run build): node scripts/seo/discover-audit.ts
 */
import * as fs from 'fs';
import * as path from 'path';

const DIST = path.resolve(process.cwd(), 'dist', 'client');
const REPORT = path.resolve(process.cwd(), 'docs', 'seo', 'discover-audit.md');
const MIN_WIDTH = 1200;

type Status = 'PASS' | 'WARN' | 'UNVERIFIED';
interface Row {
  page: string;
  ogImage: { url: string; status: Status; note: string };
  schemaImage: { url: string; status: Status; note: string };
}

function walkHtml(dir: string, cb: (p: string) => void): void {
  if (!fs.existsSync(dir)) return;
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) walkHtml(full, cb);
    else if (e.isFile() && e.name.endsWith('.html')) cb(full);
  }
}

/**
 * TOP-LEVEL Article nodes only: archives (CollectionPage) nest `hasPart`
 * Article stubs — those are NOT article pages and must not be audited
 * (they'd all warn "no image emitted" as false positives).
 */
function topLevelArticles(html: string): { found: boolean; image: string | null } {
  let found = false;
  let image: string | null = null;
  for (const m of html.matchAll(/<script type="application\/ld\+json">([\s\S]*?)<\/script>/g)) {
    try {
      const data = JSON.parse(m[1]);
      const nodes = Array.isArray(data) ? data : [data];
      for (const n of nodes) {
        // @type may be a string OR an array (YMYL pages: ["MedicalWebPage","Article"]).
        const t = n && typeof n === 'object' ? (n as { '@type'?: string | string[] })['@type'] : undefined;
        const isArticle = t === 'Article' || (Array.isArray(t) && t.includes('Article'));
        if (isArticle) {
          found = true;
          const img = (n as { image?: unknown }).image;
          if (typeof img === 'string') image = img;
          else if (img && typeof img === 'object' && 'url' in (img as object)) image = String((img as { url: unknown }).url);
        }
      }
    } catch {
      /* unparseable JSON-LD is validate-jsonld's job, not ours */
    }
  }
  return { found, image };
}

async function classify(url: string): Promise<{ status: Status; note: string }> {
  if (!url) return { status: 'WARN', note: 'no image emitted' };
  const u = url.replace(/^https?:\/\/[^/]+/, ''); // path within the site, if same-origin
  if (/^\/og\//.test(u)) return { status: 'PASS', note: '1200×630 by construction (OG endpoint)' };
  const local = path.join(DIST, u.replace(/^\//, '').split('?')[0]);
  if (u.startsWith('/') && fs.existsSync(local)) {
    try {
      const sharp = (await import('sharp')).default;
      const meta = await sharp(local).metadata();
      const w = meta.width ?? 0;
      return w >= MIN_WIDTH
        ? { status: 'PASS', note: `${w}×${meta.height} measured` }
        : { status: 'WARN', note: `only ${w}px wide — Discover wants ≥${MIN_WIDTH}px` };
    } catch (err) {
      return { status: 'UNVERIFIED', note: `unmeasurable: ${(err as Error).message.slice(0, 60)}` };
    }
  }
  return { status: 'UNVERIFIED', note: 'remote media — verify width ≥1200px in the CMS' };
}

async function main(): Promise<void> {
  const rows: Row[] = [];
  const pages: { page: string; html: string; image: string | null }[] = [];

  walkHtml(DIST, (filePath) => {
    const html = fs.readFileSync(filePath, 'utf-8');
    const { found, image } = topLevelArticles(html); // true article pages only
    if (!found) return;
    const page = '/' + path.relative(DIST, filePath).replace(/\\/g, '/').replace(/\/?index\.html$/, '');
    pages.push({ page, html, image });
  });

  for (const { page, html, image } of pages) {
    const og = html.match(/<meta property="og:image" content="([^"]+)"/)?.[1] ?? '';
    rows.push({
      page,
      ogImage: { url: og, ...(await classify(og)) },
      schemaImage: { url: image ?? '', ...(await classify(image ?? '')) },
    });
  }

  const warns = rows.filter((r) => r.ogImage.status === 'WARN' || r.schemaImage.status === 'WARN');
  const stamp = new Date().toISOString();

  const md = `# Google Discover image audit

> Generated by \`scripts/seo/discover-audit.ts\` (P15-P4b). Non-blocking.
> Last run: ${stamp} · Pages audited: ${rows.length} · Warnings: ${warns.length}

Discover eligibility wants hero/social images **≥ ${MIN_WIDTH}px wide** plus
\`max-image-preview:large\` (emitted sitewide by SEO.astro).

| Article page | og:image | Article schema image |
|---|---|---|
${rows
  .map(
    (r) =>
      `| ${r.page} | ${r.ogImage.status} — ${r.ogImage.note} | ${r.schemaImage.status} — ${r.schemaImage.note} |`,
  )
  .join('\n')}

## Legend
- **PASS** — provably ≥${MIN_WIDTH}px (measured, or an OG endpoint that renders 1200×630).
- **WARN** — provably undersized; replace the hero with a ≥${MIN_WIDTH}px asset.
- **UNVERIFIED** — remote CMS media the build can't measure offline; confirm in the CMS.
`;

  fs.mkdirSync(path.dirname(REPORT), { recursive: true });
  fs.writeFileSync(REPORT, md);

  console.log(`discover-audit: ${rows.length} article pages, ${warns.length} warnings → ${path.relative(process.cwd(), REPORT)}`);
  for (const r of warns) console.warn(`  ⚠ ${r.page}: og=${r.ogImage.note} schema=${r.schemaImage.note}`);

  if (warns.length && process.env.DISCOVER_AUDIT_STRICT === 'true') process.exit(1);
}

main().catch((err) => {
  // Non-blocking by decree — an audit crash must never fail the build.
  console.error('discover-audit: crashed (non-blocking):', (err as Error).message);
});
